spring:
  application:
    name: server
  datasource:
    url: jdbc:postgresql://localhost:5432/myvid
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: sdfkdsfdke-csdfe-erer-serersdfewr-sdfsdf-erew-sdfre
aws:
  sqs:
    video-processing:
      queue-url: my-vid-video-processing-queue
    processed-video:
      queue-url: my-vid-video-processed-queue
  s3:
    enabled: true
    type: local
    video-processing:
      bucket-name: my-vid-video-processing-bucket
    processed-video:
      bucket-name: my-vid-video-processed-bucket
    region: us-east-1
  access-key: test
  secret-key: test
  endpoint: http://localhost:4566