aws:
  sqs:
    data-processing:
      queue-url: http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/my-vid-data-processing-queue
    processed-data:
      queue-url: http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/my-vid-processed-data-queue
  s3:
    data-processing:
      bucket-name: my-vid-data-processing-bucket
    processed-data:
      bucket-name: my-vid-data-processed-bucket
  temp-store:
    video:
      src: "./temp/src/video/"
      dest: "./temp/dest/video/"
    image:
      src: "./temp/src/image/"
      dest: "./temp/dest/image/"
  region: us-east-1
  access-key: test
  secret-key: test
  pathAccess: true
  endpoint: http://localhost:4566
