aws:
  sqs:
    video-processing:
      queue-name: my-vid-video-processing-queue
    processed-video:
      queue-name: my-vid-video-processed-queue
  s3:
    enabled: true
    type: local
    video-processing:
      bucket-name: my-vid-video-processing-bucket
    processed-video:
      bucket-name: my-vid-video-processed-bucket
    region: us-east-1
  access-key: test
  secret-key: test
  endpoint: http://localhost:4566
